### ISSUE TITLE
Setup GitHub Actions CI and semantic release

### ISSUE THREAD

**Issue by hsluoyz** [jcasbin/play-authz#3]
Refer to: https://github.com/jcasbin/jdbc-adapter/pull/40

**Comment by hsluoyz** [comment]
@offset-null1

**Comment by offset-null1** [comment]
Hi @hsluoyz, can I use gradle as the build tool instead of sbt? Also, can you please provide details?

**Comment by hsluoyz** [comment]
See what tool Play developers use. This repo is for Play developers
